### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by gustavoSoriano** [jco666/Vue-RLS#1]
Olá, blz ? 
cara, curti sua biblioteca. O david me mostrou, fiquei maravilhado e gostaria de sugerir o uso
de addEventListener("storage") https://developer.mozilla.org/en-US/docs/Web/API/StorageEvent,
dessa forma vc conseguiria tratar melhor a reatividade, mesmo que alguém altere o localstorage manualmente por exemplo. É um evento bastante útil. Abraço.

**Comment by jco666** [comment]
Vou estudar e ver como implementar, vlw pela dica !
